### ISSUE TITLE
Can't add a new key into hash during iteration - Ruby 2.5.7, Rails 5.1.6.2, Sidekiq 6.0.0

### ISSUE THREAD

**Issue by simonireilly** [gmac/sidekiq-heroku-autoscale#2]
Hi, Getting a bug, not on boot but when requests are made to my App.

- Running Sidekiq 6 with Sidekiq enterprise
- Using basic auth in sidekiq

initializers/sidekiq.rb
```ruby
config = YAML.safe_load(ERB.new(File.read("#{Rails.root}/config/sidekiq_heroku_autoscale.yml")).result)
Sidekiq::HerokuAutoscale.init(config)
```

sidekiq_heroku_autoscale.yml
```yaml
# All config options https://github.com/gmac/sidekiq-heroku-autoscale#plugin-config

api_token: <%= ENV["HEROKU_API_KEY"] %>
app_name: <%= ENV["HEROKU_APP_NAME"] %>
processes:
  worker:
    system:
      watch_queues:
        - default
      include_retrying: true
      include_scheduled: false
    scale:
      mode: binary
      max_dynos: 2
  worker_search_indexing:
    system:
      watch_queues:
        - chewy
        - search_indexing
      include_retrying: true
      include_scheduled: false
    scale:
      mode: binary
      max_dynos: 1
  worker_cache_expiry:
    system:
      watch_queues:
        - cache_expiry
      include_retrying: true
      include_scheduled: false
    scale:
      mode: binary
      max_dynos: 1
  worker_bulk_ops:
    system:
      watch_queues:
        - import
        - bulk_export
        - post_import
        - bulk_event_produce
      include_retrying: true
      include_scheduled: false
    scale:
      mode: binary
      max_dynos: 1
  worker_fast:
    system:
      watch_queues:
        - email_notifications
        - webhooks
        - events
      include_retrying: true
      include_scheduled: false
    scale:
      mode: binary
      max_dynos: 1
  worker_slow:
    system:
      watch_queues:
        - slow
      include_retrying: true
      include_scheduled: false
    scale:
      mode: binary
      max_dynos: 1
  worker_periodic:
    system:
      watch_queues:
        - periodic
      include_retrying: true
      include_scheduled: true
    scale:
      mode: binary
      max_dynos: 1
```

routes.rb
```ruby
require "sidekiq/web"
require "sidekiq/heroku_autoscale/web"
require "sidekiq-ent/web"

def mount_sidekiq_monitoring
  # mount freely in development.
  if Rails.env.development?
    mount Sidekiq::Web, at: "/sidekiq"
  # otherwise, only mount if username/password are defined
  elsif ENV["SIDEKIQ_USERNAME"].present? && ENV["SIDEKIQ_PASSWORD"].present?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
    end
    mount Sidekiq::Web, at: "/sidekiq"
  end
end
```

When deployed in my application I have the following error stacktrace

```bash
RuntimeError: can't add a new key into hash during iteration
  from sidekiq/heroku_autoscale/poll_interval.rb:14:in `call'
  from sidekiq/heroku_autoscale/process.rb:63:in `ping!'
  from sidekiq/heroku_autoscale/heroku_app.rb:52:in `each'
  from sidekiq/heroku_autoscale/heroku_app.rb:52:in `ping!'
  from sidekiq/heroku_autoscale/web_extension.rb:17:in `block in registered'
  from sidekiq/web/application.rb:289:in `instance_exec'
  from sidekiq/web/application.rb:289:in `block in call'
  from sidekiq/web/application.rb:287:in `catch'
  from sidekiq/web/application.rb:287:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/auth/basic.rb:28:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/auth/basic.rb:28:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/protection/xss_header.rb:18:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/protection/base.rb:50:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/protection/base.rb:50:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/protection/path_traversal.rb:16:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/protection/json_csrf.rb:26:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/protection/base.rb:50:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/protection/base.rb:50:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/protection/frame_options.rb:31:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/protection/base.rb:50:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/session/abstract/id.rb:269:in `context'
  from rack/session/abstract/id.rb:263:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/urlmap.rb:77:in `block in call'
  from rack/urlmap.rb:61:in `each'
  from rack/urlmap.rb:61:in `call'
  from rack/builder.rb:177:in `call'
  from sidekiq/web.rb:104:in `call'
  from sidekiq/web.rb:109:in `call'
  from action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
  from action_dispatch/routing/mapper.rb:46:in `serve'
  from action_dispatch/journey/router.rb:50:in `block in serve'
  from action_dispatch/journey/router.rb:33:in `each'
  from action_dispatch/journey/router.rb:33:in `serve'
  from action_dispatch/routing/route_set.rb:844:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from new_relic/rack/agent_hooks.rb:30:in `traced_call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/deflater.rb:45:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:34:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/etag.rb:27:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/conditional_get.rb:27:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/head.rb:14:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from lib/compressed_requests.rb:28:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from lib/store_request_id.rb:26:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from cacheable_flash/middleware.rb:13:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/session/abstract/id.rb:269:in `context'
  from rack/session/abstract/id.rb:263:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/cookies.rb:613:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/callbacks.rb:26:in `block in call'
  from active_support/callbacks.rb:97:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:24:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:59:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from chewy/railtie.rb:19:in `block in call'
  from chewy/strategy.rb:70:in `wrap'
  from chewy.rb:201:in `strategy'
  from chewy/railtie.rb:19:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from lib/verify_ip_address_against_whitelist.rb:27:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from penthouse/app.rb:34:in `block in call'
  from penthouse/runners/base_runner.rb:29:in `block (2 levels) in call'
  from penthouse.rb:34:in `with_tenant'
  from penthouse/runners/base_runner.rb:28:in `block in call'
  from penthouse/tenants/schema_tenant.rb:44:in `call'
  from penthouse/tenants/octopus_schema_tenant.rb:24:in `block in call'
  from penthouse/tenants/octopus_schema_tenant.rb:52:in `block in switch_shard'
  from octopus/proxy.rb:86:in `block (2 levels) in run_queries_on_shard'
  from octopus/proxy.rb:314:in `using_shard'
  from octopus/proxy.rb:85:in `block in run_queries_on_shard'
  from octopus/proxy.rb:298:in `keeping_connection_proxy'
  from octopus/proxy.rb:84:in `run_queries_on_shard'
  from octopus.rb:136:in `using'
  from penthouse/tenants/octopus_schema_tenant.rb:51:in `switch_shard'
  from penthouse/tenants/octopus_schema_tenant.rb:24:in `call'
  from penthouse/tenants/octopus_shard_tenant.rb:31:in `call'
  from penthouse/runners/base_runner.rb:27:in `call'
  from penthouse/app.rb:33:in `call'
  from config/initializers/penthouse.rb:65:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from lograge/rails_ext/rack/logger.rb:15:in `call_app'
  from rails/rack/logger.rb:24:in `block in call'
  from active_support/tagged_logging.rb:69:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:69:in `tagged'
  from rails/rack/logger.rb:24:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from admin_ip_whitelist.rb:16:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/remote_ip.rb:79:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from request_store/middleware.rb:19:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/request_id.rb:25:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/method_override.rb:24:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/runtime.rb:24:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/executor.rb:12:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/static.rb:125:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/sendfile.rb:113:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/ssl.rb:68:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rails/engine.rb:522:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from puma/configuration.rb:225:in `call'
  from puma/server.rb:658:in `handle_request'
  from puma/server.rb:472:in `process_client'
  from puma/server.rb:332:in `block in run'
  from puma/thread_pool.rb:133:in `block in spawn_thread'
```
