### ISSUE TITLE
Cannot invoke worker command on Heroku

### ISSUE THREAD

**Issue by StephyMilkyCat** [gmac/sidekiq-heroku-autoscale#8]
@gmac 
I have the following workers in `Procfile`:
```
web: bundle exec puma -C config/puma.rb
worker: bundle exec sidekiq -C config/sidekiq/standard.yml
worker_medium: bundle exec sidekiq -C config/sidekiq/medium.yml
worker_large: bundle exec sidekiq -C config/sidekiq/large.yml
worker_xlarge: bundle exec sidekiq -C config/sidekiq/xlarge.yml
```

config/sidekiq/standard.yml:
```
:timeout: 25
:pidfile: tmp/pids/sidekiq/standard.pid
:logfile: log/sidekiq/standard.log
development:
  :concurrency: 1
staging:
  :concurrency: 1
production:
  :concurrency: 1
:queues:
  - [default, 4]
```

config/sidekiq/medium.yml:
```
:timeout: 25
:pidfile: tmp/pids/sidekiq/medium.pid
:logfile: log/sidekiq/medium.log
development:
  :concurrency: 1
staging:
  :concurrency: 1
production:
  :concurrency: 1
:queues:
  - [medium, 4]
```

config/sidekiq/large.yml:
```
:timeout: 25
:pidfile: tmp/pids/sidekiq/large.pid
:logfile: log/sidekiq/large.log
development:
  :concurrency: 1
staging:
  :concurrency: 1
production:
  :concurrency: 1
:queues:
  - [large, 4]
```

config/sidekiq/xlarge.yml:
```
:timeout: 25
:pidfile: tmp/pids/sidekiq/xlarge.pid
:logfile: log/sidekiq/xlarge.log
development:
  :concurrency: 1
staging:
  :concurrency: 1
production:
  :concurrency: 1
:queues:
  - [xlarge, 4]
```

heroku_autoscale.yml:
```
throttle: 12
history: 3600
processes:
  worker:
    system:
      watch_queues:
        - mailers
        - default
      include_retrying: false
      include_scheduled: false
    scale:
      mode: linear
      max_dynos: 100
      min_dynos: 1
      workers_per_dyno: 1
      min_factor: 0
    quiet_buffer: 10
  worker_medium:
    system:
      watch_queues:
        - medium
      include_retrying: false
      include_scheduled: false
    scale:
      mode: linear
      max_dynos: 100
      min_dynos: 0
      workers_per_dyno: 1
      min_factor: 0
    quiet_buffer: 10
  worker_large:
    system:
      watch_queues:
        - large
      include_retrying: false
      include_scheduled: false
    scale:
      mode: linear
      max_dynos: 100
      min_dynos: 0
      workers_per_dyno: 1
      min_factor: 0
    quiet_buffer: 10
  worker_xlarge:
    system:
      watch_queues:
        - xlarge
      include_retrying: false
      include_scheduled: false
    scale:
      mode: linear
      max_dynos: 100
      min_dynos: 0
      workers_per_dyno: 1
      min_factor: 0
    quiet_buffer: 10
```

each worker is watching an independent queue, and I have 4 classes with specifying `sidekiq_options queue: default | medium | large | xlarge`

And I am using Heroku professional dynos, but when I call those classes, I cannot see the `bundle exec sidekiq -C config/sidekiq/xxxx.yml` is invoked via `heroku logs --tail`, and of course the designated worker is never switched on.

Any idea?
